name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    name: Run Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest PyGithub
      - name: Test with pytest
        run: |
          pytest
